# Generated by Django 5.1.6 on 2025-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_total', models.BigIntegerField()),
                ('memory_used', models.BigIntegerField()),
                ('memory_free', models.BigIntegerField()),
            ],
        ),
    ]
