# Generated by Django 5.1.6 on 2025-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_recv', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_recv', models.BigIntegerField()),
            ],
        ),
    ]
