# Generated by Django 5.1.6 on 2025-03-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_networkmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmetrics',
            name='bytes_recv_speed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetrics',
            name='bytes_sent_speed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetrics',
            name='dropin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetrics',
            name='dropout',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetrics',
            name='errin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetrics',
            name='errout',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='create_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='io_read_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='io_write_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='memory_rss',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='memory_vms',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='cpu_freq',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='cpu_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='disk_free',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='disk_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='disk_total',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='disk_used',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='memory_buffers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='memory_cached',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='swap_total',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='swap_used',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=50, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('speed', models.IntegerField(null=True)),
                ('network_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='monitoring.networkmetrics')),
            ],
        ),
    ]
